FR-10106 - fix imports with new tree shake structure
frontegg/frontegg-nextjs pull request #117
Opened 2022-12-21 14:13 UTC by yuvalotem1

### fix imports with new tree shake structure

After changing nextjs package to be tree-shakeable these error appeared using alpha - 
<img width="1028" alt="Screenshot 2022-12-21 at 16 11 42" src="https://user-images.githubusercontent.com/106734943/208925168-270591ed-85cd-4b7d-9c5d-05c7ddaf9d60.png">
The fix would be adding `"type": "module"` to `package.json`

2022-12-21 23:25 UTC, frontegg-david requested changes

2022-12-21 23:25 UTC, frontegg-david commented on packages/nextjs/src/common/types.ts
> +import { NextRouter } from 'next/router.js';
what is the purpose of .js?

2022-12-22 09:00 UTC, yuvalotem1 commented on packages/nextjs/src/common/types.ts
> +import { NextRouter } from 'next/router.js';
removed

2022-12-22 10:24 UTC, frontegg-david approved these changes

2022-12-22 11:11 UTC, merged